name: healthtracker
description: A health tracker app

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  provider: ^6.1.5+1
  google_sign_in: ^6.2.1
  intl: ^0.20.2
  flutter_local_notifications: ^20.0.0
  timezone: ^0.10.1
  flutter_timezone: ^5.0.1
  firebase_storage: ^11.6.0
  file_picker: ^8.0.0
  url_launcher: ^6.2.0
  uuid: ^4.5.2
  shared_preferences: ^2.5.4
  flutter_localizations:
    sdk: flutter
  google_fonts: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
